services:
  api:
    build: ./
    container_name: order-service-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_db
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_password
      RBHOST: rabbitmq      
      RBPORT: 5672      
      REDIS_HOST: redis
      REDIS_PORT: 6379
  postgres:
    image: postgres:15
    container_name: order-service-db
    restart: always
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: order-service-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Porta para comunicação entre serviços
      - "15672:15672" # UI Web do RabbitMQ
  
  redis:
    image: redis:7
    container_name: order-service-redis
    restart: always
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: order-service-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: order-service-grafana
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data:
